/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package software.project;

import javax.swing.JOptionPane;

/**
 *
 * @author Mustafa-Sokar
 */
public class Update_Information extends javax.swing.JFrame {

    /**
     * Creates new form User_Information
     */
    public Update_Information(int x,int y) {
        initComponents();
        
        this.setTitle("Update Information");
         this.setLocationRelativeTo(null);
        this.jLabel9.hide();
        this.jLabel10.hide();
        this.pass.hide();
        this.confirmpass.hide();
        this.setSize(800,450);
        this.setSize(x,y);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FirstN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LastN = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Phone = new javax.swing.JTextField();
        Datebirth = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        confirmpass = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        newPass = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        setPreferredSize(new java.awt.Dimension(537, 489));

        jPanel1.setBackground(new java.awt.Color(60, 82, 90));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 51, -1, -1));

        FirstN.setBackground(new java.awt.Color(255, 235, 255));
        FirstN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FirstN.setText("mostafa");
        FirstN.setToolTipText("");
        FirstN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNActionPerformed(evt);
            }
        });
        jPanel1.add(FirstN, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 53, 150, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 51, -1, -1));

        LastN.setBackground(new java.awt.Color(255, 235, 255));
        LastN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LastN.setText("Sokar");
        LastN.setToolTipText("");
        LastN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNActionPerformed(evt);
            }
        });
        jPanel1.add(LastN, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 53, 150, -1));

        email.setBackground(new java.awt.Color(255, 235, 255));
        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.setText("mostafa@gmail.com");
        email.setToolTipText("");
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 96, 150, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 94, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 94, -1, -1));

        Phone.setBackground(new java.awt.Color(255, 235, 255));
        Phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Phone.setText("0592979196");
        Phone.setToolTipText("");
        Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneActionPerformed(evt);
            }
        });
        Phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PhoneKeyPressed(evt);
            }
        });
        jPanel1.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 96, 150, -1));

        Datebirth.setToolTipText("");
        jPanel1.add(Datebirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 147, 150, 29));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date of Birth:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 147, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gender:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 148, -1, -1));

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setSelected(true);
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 147, -1, -1));

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 147, -1, -1));

        jLabel7.setText("--------------------------------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 194, 562, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" Password:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 272, -1, -1));

        pass.setBackground(new java.awt.Color(255, 235, 255));
        pass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pass.setToolTipText("");
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 274, 140, -1));

        confirmpass.setBackground(new java.awt.Color(255, 235, 255));
        confirmpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirmpass.setToolTipText("");
        confirmpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpassActionPerformed(evt);
            }
        });
        jPanel1.add(confirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 274, 140, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Confirm Password:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 272, -1, -1));

        newPass.setBackground(new java.awt.Color(192, 57, 43));
        newPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newPass.setText("Set New Password");
        newPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newPassMouseClicked(evt);
            }
        });
        jPanel1.add(newPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 221, -1, -1));

        jButton1.setBackground(new java.awt.Color(144, 167, 140));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 320, 152, 52));

        jLabel14.setBackground(new java.awt.Color(51, 51, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/project/user_p-modified.png"))); // NOI18N
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirstNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNActionPerformed

    private void LastNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void confirmpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpassActionPerformed

    private void newPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newPassMouseClicked
        // TODO add your handling code here:
        
        this.jLabel9.setVisible(true);
        this.jLabel10.setVisible(true);
        this.pass.setVisible(true);
        this.confirmpass.setVisible(true);
    }//GEN-LAST:event_newPassMouseClicked

    private void PhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhoneKeyPressed
        // TODO add your handling code here:
        
           char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            this.Phone.setEditable(false);
              JOptionPane.showMessageDialog(null, "Please Enter Number Only");
        }
        else {
             this.Phone.setEditable(true);
        }
    }//GEN-LAST:event_PhoneKeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
         if(this.FirstN.getText().isEmpty()||this.LastN.getText().isEmpty()
            ||this.email.getText().isEmpty()||this.Phone.getText().isEmpty()||this.pass.getText().isEmpty()||this.confirmpass.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please Fill all the Fields");
            }
        
      
       else if(!(this.pass.getText().equals(this.confirmpass.getText()))){
            JOptionPane.showMessageDialog(null, "Mismatch Passwords");
        }
         
       else{
           JOptionPane.showMessageDialog(null, "Updated successfully");
           
           //store in database
           
           
           
       }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Update_Information gg=new Update_Information(850,450);
                        gg.setVisible(true);
                        gg.setSize(850,450);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Datebirth;
    private javax.swing.JTextField FirstN;
    private javax.swing.JTextField LastN;
    private javax.swing.JTextField Phone;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField confirmpass;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton male;
    private javax.swing.JButton newPass;
    private javax.swing.JTextField pass;
    // End of variables declaration//GEN-END:variables
}
