/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package software.project;

import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mustafa-Sokar
 */
public class Update_Information extends javax.swing.JFrame {

    /**
     * Creates new form User_Information
     */
    String username;
    public Update_Information(int x,int y,String[] info) {
        try {
            initComponents();
            
            this.setTitle("Update Information");
            this.setLocationRelativeTo(null);
            this.jLabel9.hide();
            this.jLabel10.hide();
            this.pass.hide();
            this.checkbox1.hide();
            this.checkbox2.hide();
            this.confirmpass.hide();
            this.setSize(800,550);
            this.setSize(x,y);
            username = info[0];
            this.user.setText(info[0]);
            this.FN.setText(info[1]);
            this.LN.setText(info[2]);
            this.email.setText(info[4]);
            this.Phone.setText("0"+info[5]);
            this.city.setText(info[6]);
            this.Datebirth.setDate(User.getBirth(info[0]));
            if(info[7].equals("M")){
                this.male.setSelected(true);
                this.female.setSelected(false);
            }else {
                this.male.setSelected(false);
                this.female.setSelected(true);
            }} catch (SQLException ex) {
            Logger.getLogger(Update_Information.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LN = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Phone = new javax.swing.JTextField();
        Datebirth = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        newPass = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        checkbox1 = new java.awt.Checkbox();
        checkbox2 = new java.awt.Checkbox();
        pass = new javax.swing.JPasswordField();
        confirmpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        setPreferredSize(new java.awt.Dimension(537, 489));

        jPanel1.setBackground(new java.awt.Color(60, 82, 90));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 51, -1, -1));

        FN.setBackground(new java.awt.Color(255, 235, 255));
        FN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FN.setText("mostafa");
        FN.setToolTipText("");
        FN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNActionPerformed(evt);
            }
        });
        jPanel1.add(FN, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 53, 150, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 51, -1, -1));

        LN.setBackground(new java.awt.Color(255, 235, 255));
        LN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LN.setText("Sokar");
        LN.setToolTipText("");
        LN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNActionPerformed(evt);
            }
        });
        jPanel1.add(LN, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 53, 150, -1));

        email.setBackground(new java.awt.Color(255, 235, 255));
        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.setText("mostafa@gmail.com");
        email.setToolTipText("");
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 96, 150, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 94, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 94, -1, -1));

        Phone.setBackground(new java.awt.Color(255, 235, 255));
        Phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Phone.setText("0592979196");
        Phone.setToolTipText("");
        Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneActionPerformed(evt);
            }
        });
        Phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PhoneKeyPressed(evt);
            }
        });
        jPanel1.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 96, 150, -1));

        Datebirth.setToolTipText("");
        jPanel1.add(Datebirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 147, 150, 29));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date of Birth:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 147, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gender:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 148, -1, -1));

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setSelected(true);
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 147, -1, -1));

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 147, -1, -1));

        jLabel7.setText("--------------------------------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 562, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" Password:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Confirm Password:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        newPass.setBackground(new java.awt.Color(192, 57, 43));
        newPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newPass.setText("Set New Password");
        newPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newPassMouseClicked(evt);
            }
        });
        newPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPassActionPerformed(evt);
            }
        });
        jPanel1.add(newPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jButton1.setBackground(new java.awt.Color(144, 167, 140));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 152, 52));

        jLabel14.setBackground(new java.awt.Color(51, 51, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/project/User_Icon.png"))); // NOI18N
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        city.setBackground(new java.awt.Color(255, 235, 255));
        city.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        city.setText("Nablus");
        city.setToolTipText("");
        jPanel1.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 150, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("City:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        user.setBackground(new java.awt.Color(255, 235, 255));
        user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user.setText("MustafaSokar");
        user.setToolTipText("");
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 150, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("User Name:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        checkbox1.setForeground(new java.awt.Color(255, 255, 255));
        checkbox1.setLabel("Show");
        checkbox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox1ItemStateChanged(evt);
            }
        });
        jPanel1.add(checkbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        checkbox2.setForeground(new java.awt.Color(255, 255, 255));
        checkbox2.setLabel("Show");
        checkbox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox2ItemStateChanged(evt);
            }
        });
        jPanel1.add(checkbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, -1, -1));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 120, 30));
        jPanel1.add(confirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNActionPerformed

    private void LNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    boolean changingPass = false;
    
    private void newPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newPassMouseClicked
        // TODO add your handling code here:
        
        this.jLabel9.setVisible(true);
        this.jLabel10.setVisible(true);
        this.pass.setVisible(true);
        this.confirmpass.setVisible(true);
        this.checkbox1.setVisible(true);
        this.checkbox2.setVisible(true);
        this.changingPass = true;
       
    }//GEN-LAST:event_newPassMouseClicked

    private void PhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhoneKeyPressed
        // TODO add your handling code here:
        
           char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            this.Phone.setEditable(false);
              JOptionPane.showMessageDialog(null, "Please Enter Number Only");
        }
        else {
             this.Phone.setEditable(true);
        }
    }//GEN-LAST:event_PhoneKeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        boolean pass = this.pass.getText().isEmpty()||this.confirmpass.getText().isEmpty();
        boolean restFields = this.FN.getText().isEmpty()||this.LN.getText().isEmpty()
            ||this.email.getText().isEmpty()||this.Phone.getText().isEmpty();
         if(restFields || pass && this.changingPass)
            {
                JOptionPane.showMessageDialog(null, "Please Fill all the Fields");
            }
       else if(!(this.pass.getText().equals(this.confirmpass.getText()))){
            JOptionPane.showMessageDialog(null, "Mismatch Passwords");
        }
         
       else{

           
           //store update in database...
           // checking if there is a password update

           // user,first,last,email,phone,address,gender
           String[] info = new String[7];
           info[0] = this.user.getText();
           info[1] = this.FN.getText();
           info[2] = this.LN.getText();
           info[3] = this.email.getText();
           info[4] = this.Phone.getText();
           info[5] = this.city.getText();
           if(this.male.isSelected())
               info[6] = "M";
           else info[6] = "F";
             try {
                 boolean done2= true;
                if(this.changingPass){
                    done2=User.changePass(username,this.pass.getText());
                }
                 boolean done = User.updateUser(username, info, new java.sql.Date(this.Datebirth.getDate().getTime()));
                 if(done && done2){
                     JOptionPane.showMessageDialog(rootPane,"Updated Successfully.","Information",JOptionPane.INFORMATION_MESSAGE);
                 }
             } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(rootPane,ex.toString(),"Error",JOptionPane.ERROR_MESSAGE);
             }
            
           
       }    
    }//GEN-LAST:event_jButton1MouseClicked

    private void checkbox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox1ItemStateChanged
        // TODO add your handling code here:
        if(this.checkbox1.getState()){
            this.pass.setEchoChar((char)0);
        }
        else{
            this.pass.setEchoChar('*');
        }
    }//GEN-LAST:event_checkbox1ItemStateChanged

    private void checkbox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox2ItemStateChanged
        // TODO add your handling code here:
        
         if(this.checkbox2.getState()){
            this.confirmpass.setEchoChar((char)0);
        }
        else{
            this.confirmpass.setEchoChar('*');
        }
    }//GEN-LAST:event_checkbox2ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void newPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPassActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Datebirth;
    private javax.swing.JTextField FN;
    private javax.swing.JTextField LN;
    private javax.swing.JTextField Phone;
    private javax.swing.ButtonGroup buttonGroup1;
    private java.awt.Checkbox checkbox1;
    private java.awt.Checkbox checkbox2;
    private javax.swing.JTextField city;
    private javax.swing.JPasswordField confirmpass;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton male;
    private javax.swing.JButton newPass;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
